import './click'
import './mouseenter'
import './mouseleave'
import './cut'
import './keydown'
import './keypress'
import './keyup'
import './paste'

export {behavior} from './registry'
export type {BehaviorPlugin} from './registry'
