name: Chore
on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 🧹🪣 Delete caches
        run: gh cache delete --all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
